<?php
/**
 * Copyright © Magexperts (support@magexperts.com). All rights reserved.
 * Please visit Magexperts.com for license details (https://magexperts.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block \Magexperts\Community\Block\JsScript
 * @var $mfSecureRenderer \Magexperts\Community\Api\SecureHtmlRendererInterface
 */
?>
<?php $script = "
    window.MagexpertsJs = window.MagexpertsJs || {};
    window.MagexpertsJs.ajax = function(options) {
        var xmlhttp = new XMLHttpRequest();
        xmlhttp.onreadystatechange = function () {
            if (xmlhttp.readyState == XMLHttpRequest.DONE && xmlhttp.status == 200) {
                var data = xmlhttp.responseText;
                if (options.success) options.success(data);
            }
        };

        xmlhttp.open(options.type, options.url, true);

        var requestHeader = Object.assign({}, {
            'X-Requested-With': 'XMLHttpRequest',
            'Content-type': 'application/x-www-form-urlencoded'
        }, options.requestHeader ? options.requestHeader : {});

        for (var header in requestHeader) {
            xmlhttp.setRequestHeader(header, requestHeader[header]);
        }
        xmlhttp.send(options.data);
    };
"; ?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
