<?php
/**
 * Magexperts Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://magexperts.com/Magexperts-License.txt
 *
 * @category  Magexperts
 * @package   Magexperts_FacebookPixel
 * @author    Extension Team
 * @copyright Copyright (c) 2018-2019 Magexperts Co. ( http://magexperts.com )
 * @license   http://magexperts.com/Magexperts-License.txt
 */
?>
<div data-role="bss-fbpixel-atc" style="display:none;">

</div>
<script type="text/x-magento-init">
    {
        "[data-role='bss-fbpixel-atc']":
            {
                "Magento_Ui/js/core/app": <?= $block->getJsLayout();?>
            }
    }
</script>
