<?php
/**
 * Copyright © Magexperts (support@magexperts.com). All rights reserved.
 * Please visit Magexperts.com for license details (https://magexperts.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post links template
 *
 * @var $block \Magexperts\Blog\Block\Post\PostLinks
 */
?>
<?php
    $postCollection = $block->getPostCollection();
?>
<?php if (!$postCollection->count()) { ?>
    <div class="message info empty">
        <div>
            <?= $block->escapeHtml(__('We can\'t find posts matching the selection.')) ?>
        </div>
    </div>
<?php } else { ?>
    <?= $block->getAdditionalHtml() ?>
    <div class="post-links-wrapper">
        <?php $iterator = 1; ?>
        <ul class="post-links">
            <?php foreach ($postCollection as $post): ?>
                <li>
                    <?php $postTitle = $post->getTitle() ?>
                    <a href="<?= $block->escapeUrl($post->getPostUrl()) ?>"
                       title="<?= $block->escapeHtml($postTitle) ?>">
                        <?= $block->escapeHtml($postTitle) ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php } ?>

