<?php
/**
 * Magexperts Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://magexperts.com/Magexperts-License.txt
 *
 * @category   Magexperts
 * @package    Magexperts_Quickview
 * @author     Extension Team
 * @copyright  Copyright (c) 2019-2020 Magexperts Co. ( http://magexperts.com )
 * @license    http://magexperts.com/Magexperts-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var \Magexperts\Quickview\Block\Initialize $block
 */
?>
<?php $product = $block->getProduct(); ?>
<?php
    $helper = $block->getHelper();
    $removeReview = $helper->getRemoveReview();
    $removeMoreInfo = $helper->getRemoveMoreInfo();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Magexperts_Quickview/js/bss_beforebodyend": {
                "removeReview": "<?php echo $removeReview; ?>",
                "removeMoreInfo": "<?php echo $removeMoreInfo; ?>"
            }
        }
    }
</script>
