<?php
/**
 * Magexperts Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://magexperts.com/Magexperts-License.txt
 *
 * @category   Magexperts
 * @package    Magexperts_Quickview
 * @author     Extension Team
 * @copyright  Copyright (c) 2019-2020 Magexperts Co. ( http://magexperts.com )
 * @license    http://magexperts.com/Magexperts-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var Magento\Catalog\Block\Product\View\Type\Simple $block
 */
?>
<?php $product = $block->getProduct();
?>
<div id="ajax-goto">
    <a class="goto-product" href="<?php echo $product->getUrlModel()->getUrl($product);?>">
        <span><?php echo __('Go to Product'); ?></span>
    </a>
</div>
