<?php
/**
 * Copyright © Magexperts (support@magexperts.com). All rights reserved.
 * Please visit Magexperts.com for license details (https://magexperts.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php /** @var $mfSecureRenderer \Magexperts\Community\Api\SecureHtmlRendererInterface */ ?>
<?php $script = "
    require(['jquery', 'domReady!'], function ($) {
        var isLoadedInterval = setInterval(isLoaded, 2000);

        function isLoaded() {
            var el = $('[data-index=\"related\"] .admin__data-grid-pager-wrap');

            if (el.length) {
                $('[data-index=\"related\"] .admin__data-grid-pager-wrap').click(function () {
                    $('[data-index=\"related\"] [data-role=\"spinner\"]').show();
                    setTimeout(function () {
                        $('[data-index=\"related\"] [data-role=\"spinner\"]').hide();
                    }, 5000);
                });

                clearInterval(isLoadedInterval);
            }
        }
    });
"; ?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>