<?php
/**
 * Magexperts Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://magexperts.com/Magexperts-License.txt
 *
 * @category   Magexperts
 * @package    Magexperts_Core
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 Magexperts Co. ( http://magexperts.com )
 * @license    http://magexperts.com/Magexperts-License.txt
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var $block \Magexperts\Core\Block\PreprocessedCss
 */

$cssFiles = $block->getAssetCssFiles();
$customStyles = $block->getCustomStyles();
?>
<?php if (!empty($cssFiles)): ?>
    <?php foreach ($cssFiles as $cssFile): ?>
        <link rel="stylesheet" type="text/css" media="all" href="<?= $cssFile ?>"/>
    <?php endforeach; ?>
<?php endif; ?>

<!--Custom Style-->
<?php if (!empty($customStyles)): ?>
    <style>
        <?= $customStyles ?>
    </style>
<?php endif; ?>
