<?php
/**
 * Copyright © Magexperts (support@magexperts.com). All rights reserved.
 * Please visit Magexperts.com for license details (https://magexperts.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */

/**
 * @var $block \Magexperts\Blog\Block\ViewsCount
 * @var $mfSecureRenderer \Magexperts\Community\Api\SecureHtmlRendererInterface
 */
?>
<?php $script = "
    require(['jquery', 'domReady!'], function($){
        setTimeout(function(){
            $.ajax({
                url: atob( '" . base64_encode($block->getCounterUrl()) . "'),
                type:'POST',
                dataType: 'json',
                success: function(response) { }
            })
        }, 5000);
    });
"; ?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>

