<?php
/**
 * Copyright © Magexperts (support@magexperts.com). All rights reserved.
 * Please visit Magexperts.com for license details (https://magexperts.com/end-user-license-agreement).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog category info template
 *
 * @var $block \Magexperts\Blog\Block\Index\Info
 */
?>

<?php if ($description = $block->getDescription()): ?>
    <div class="index-description"><?= /*@noEscape*/ $description ?></div>
<?php endif ?>
