<?php
/**
 * Magexperts Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://magexperts.com/Magexperts-License.txt
 *
 * @category   Magexperts
 * @package    MAGEXPERTS_HtmlSiteMap
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 Magexperts Co. ( http://magexperts.com )
 * @license    http://magexperts.com/Magexperts-License.txt
 */
?>
<?php
/**
 * SEO Toolbar template
 *
 * @var $block Magexperts\HtmlSiteMap\Block\ProductCollection
 */
?>
<?php
$helper = $block->getHelper();

//Product Link
$enableProduct = $helper->isEnableProduct();
$titleProduct = $helper->titleProduct();

if ($enableProduct) : ?>
    <h2 class="magexperts_h2"><?php echo $titleProduct; ?></h2>
    <div class="magexperts_site_map_grid">
        <?php
        $productCollection = $block->getProductCollection();
        foreach ($productCollection as $product) {
            echo $product->getData("id");
            echo '<div class="col-magexperts-3">
                    <h3 class="magexperts_product_list">
                    <a href="'.$product->getUrlModel()->getUrl($product).'"
                    title = "'.$product->getName().'">'.$product->getName().'</a>
                    </h3>
                </div>';
        }
        ?>
    </div>
    <?php
endif; ?>