<div style="background:#f8f8f8; border-top:1px solid #e3e3e3;border-bottom:1px solid #e3e3e3; margin-bottom:10px;padding:12px 0 0 12px;">
    <img src="https://www.Magexperts.com/_logo.svg" alt="Magexperts" style="height: 60px;"/><br>
    <div style="padding-left: 11px; font-size: 1.3rem;">
        <p>
            <strong style="color:#EA7601;">
                <?= /* @noEscape */ $block->getExtensionName() ?> v<?= /* @noEscape */ $block->getModuleVersion() ?> by
            </strong>
            <a target="_blank" href="https://www.Magexperts.com" title="Magexperts Store - Free / Premium Magento Extensions,  Themes &amp; Services">
                <strong>Magexperts</strong>
            </a>
        </p>
        <p>
            <?= /* @noEscape */ __('Need help? See our') ?>
            <a href="https://blog.Magexperts.com" target="_blank" title="Magexperts Blog - Tutorials, Tips &amp; Tricks for Magento, PHP, MySQL &amp; DevOps">
                <?= /* @noEscape */ __('Blog') ?>
            </a>
            <?= /* @noEscape */ __(' or contact us via') ?>
            <a href="https://www.Magexperts.com/contact" target="_blank" title="Magexperts Store - Contact Us"><?= /* @noEscape */ __('form') ?></a>.
            <?= /* @noEscape */ __(' Got feedback? ') ?>
            <a href="mailto:info@Magexperts.com?Subject=<?= $block->escapeHtml($block->getPlatform()) ?> <?= $block->escapeHtml($block->getExtensionName()) ?> <?= $block->escapeHtml($block->getModuleVersion()) ?> for <?= $block->escapeHtml($block->getMageVersion()) ?>">
                <?= /* @noEscape */ __('Email us') ?>
            </a>
        </p>

        <p style="padding-bottom: 10px;"><?= /* @noEscape */__('You can find more extensions in our') ?>
            <a href="https://www.Magexperts.com/extensions/magento-2.html" target="_blank">
                <?= /* @noEscape */ __('Store') ?>
            </a>
        </p>

        <h4>
            <a style="padding: 6px 30px 6px 30px;background-color:#EB5202; color:white; font-weight: bold;"
               href="https://www.Magexperts.com/contact" title="Magexperts Store - Contact Us" target="_blank">
                <?= /* @noEscape */ __('Need Support? Contact us') ?>
            </a>
        </h4>
    </div>
</div>
