<?php
/**
 * Copyright © Magexperts (support@magexperts.com). All rights reserved.
 * Please visit Magexperts.com for license details (https://magexperts.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block \Magexperts\Community\Block\
 * @var $mfSecureRenderer \Magexperts\Community\Api\SecureHtmlRendererInterface
 */
?>
<?php
    $mapCodeLine = '`${key0}${keysRest.map(a => `[${a}]`).join(\'\')}=${value}`)';
 ?>
<?php $script = "
    window.MagexpertsJs = window.MagexpertsJs || {};
    window.MagexpertsJs.objToUrlParams = function(obj) {
        let getPairs = (obj, keys = []) =>
            Object.entries(obj).reduce((pairs, [key, value]) => {
                if (typeof value === 'object')
                    pairs.push(...getPairs(value, [...keys, key]));
                else
                    pairs.push([[...keys, key], value]);
                return pairs;
            }, []);

        let x = getPairs(obj)
            .map(([[key0, ...keysRest], value]) =>
               {$mapCodeLine}
            .join('&');

        return x;
    };
"; ?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
