<?php
/**
 * Copyright © Magexperts (support@magexperts.com). All rights reserved.
 * Please visit Magexperts.com for license details (https://magexperts.com/end-user-license-agreement).
 */
?>
<?php
/**
 * @var $block \Magexperts\Community\Block\JsScript
 * @var $mfSecureRenderer \Magexperts\Community\Api\SecureHtmlRendererInterface
 */
?>
<?php $script = "
    window.MagexpertsJs = window.MagexpertsJs || {};
    window.MagexpertsJs.setCookie = function(name, value, params) {
        if (!name) {
            return;
        }

        params = params || {};
        
        var expires = params.expires;
        var path = params.path || '/';
        var domain = params.domain || window.location.hostname;

        var cookieString = encodeURIComponent(name) + '=' + encodeURIComponent(value);

        if (expires instanceof Date) {
            cookieString += '; expires=' + expires.toUTCString();
        }
        cookieString += '; path=' + path;
        cookieString += '; domain=' + domain;
        document.cookie = cookieString;
    };
"; ?>
<?= /* @noEscape */ $mfSecureRenderer->renderTag('script', [], $script, false) ?>
